### ISSUE TITLE
Crash: Tor together with testing server responses

### ISSUE THREAD

**Issue by HonzaR** [Electric-Coin-Company/zcash-android-wallet-sdk#1587]
The current SDK state causes the Zashi and the Demo app to crash in the scenario described below.

NOTE: It seems that only the Android API level 27 is impacted. 

NOTE 2: The crash happens only when Tor and server switching are called simultaneously.

#### If so, please list the steps to reproduce below:
1. Create Emulator API level 27
2. Run Zashi app (Demo app impacted, too)
3. Enable Currency conversion feature
4. Go to Settings -> Advanced Settings -> Choose server
5. Let the automated server responses test run and try to change server manually by clicking any available in the meantime
6. App crashes with stacktrace attached in this issue

### Actual behavior + errors
https://github.com/user-attachments/assets/5678f01c-f9a0-4947-9c0f-fe1852dd48ce

[crash_tor_server_switch_api_27.txt](https://github.com/user-attachments/files/16960495/crash_tor_server_switch_api_27.txt)

- App Version: any
- Android Version: 27
- Device: (if applies): any

### Any extra information that might be useful in the debugging process.
Reproducible on both emulators and physical devices.

**Comment by Milan-Cerovsky** [comment]
If we do not find the root cause of this issue there are two hacks coming to my mind.
1. Each Synchronizer has its own TorClient which is killed with it. Instead we can hold a static TorClient in cache to avoid its recreation
2. We can disable fetching exchange rates while fastest server calculation is ongoing

**Comment by HonzaR** [comment]
@str4d I'm attaching a new crash log file. Unfortunately, the Android SDK level 27, on which we're able to reproduce the crash, does not print the Rust trancing logs, as we recently discovered with @nuttycom. We should probably check that, too. But the new log at least adds the Kotlin logs.
[crash_api_27_logs_v2.txt](https://github.com/user-attachments/files/16992721/crash_api_27_logs_v2.txt)

**Comment by str4d** [comment]
@HonzaR explained how the server switcher works to me, and now I'm almost certain that the bug is a UAF.

In order to satisfy Rust lifetime rules, these two methods MUST NOT be called in parallel:
https://github.com/Electric-Coin-Company/zcash-android-wallet-sdk/blob/7398cbcbd7fd121e2b1d9ce2b2941bc5938acbc5/backend-lib/src/main/java/cash/z/ecc/android/sdk/internal/model/TorClient.kt#L15-L23

The problem is that:
- The `TorClient` is owned by the `Synchronizer`.
- The new server switching logic restarts the `Synchronizer`, which closes the current one, which disposes of its `TorClient` via `SdkSynchornizer.close() -> UsdExchangeRateFetcher.dispose() -> TorClientHolder.dispose() -> TorClient.dispose() -> freeTorRuntime()`.

Thus, if the app has called `Synchronizer.refreshExchangeRateUsd`, it has a mutable reference to the Tor client, and then the server switching logic attempts to free it, violating the Rust lifetime rules.

**Comment by str4d** [comment]
@HonzaR pointed me to this mutex:
https://github.com/Electric-Coin-Company/zcash-android-wallet-sdk/blob/618e8eb0122ba64ac5f2040eeb0945ece526e443/sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/exchange/UsdExchangeRateFetcher.kt#L68-L84

The mutex does not enforce the necessary Rust lifetime rules, because it only gates access to the TorClient handle, not to using it. Specifically, `invoke()` _does not_ invoke the method on `TorClient` inside the mutex:
- `TorClientHolder.invoke()` called.
  - Mutex locked.
    - `TorClient` returned.
  - Mutex unlocked
  - `TorClient.getExchangeRateUsd()` called outside mutex.
- `TorClientHolder.invoke()` called.
  - Mutex locked.
    - `TorClient.dispose()` called in parallel -> crash.

**Comment by str4d** [comment]
The fix here is to either add another Mutex inside `TorClient` itself, or pass a closure to `TorClientHolder.invoke()` that is given the `TorClient` handle while still inside the locked Mutex.

**Comment by HonzaR** [comment]
@str4d I've tried several improvements on the Kotlin side to get rid of this error on the impacted API 27. Non of it helped, unfortunately. I've also tried play a bit with threading, logged all possible states, or simplify the entire Kotlin implementation. 

It's always the same, any time we try to stop `Synchornizer`, which holds `TorClient` reference, and calls `freeTorRuntime` when disposing itself, the crash happens. The easiest way to reproduce it, is to start the Demo app (it loads currency conversion after the start automatically), and stop the Demo app by tapping the system back button, the crash comes up.

I believe that we need to handle this inside the Rust part. From my point of view as a Rust API consumer, when I use any API that provides a disposal method, then the disposal method (`freeTorRuntime` in this case) needs to check its internal running stuffs, safely stop them, stop itself, and then report the result. We as consumers should not wait until the API running is done and then dispose it, because it might take a long time, which might be true in case of this new API (loading the currency rate might take up to 20s).
